import './globals.css'
import { Inter } from 'next/font/google'
import AppContextProvider from "@/provider/AppContextProvider";
import Header from "@/components/organisms/header/Header";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <AppContextProvider>
      <body className={inter.className}>
        <Header></Header>
        <main>
          {children}
        </main>
      </body>
    </AppContextProvider>

    </html>
  )
}
