import './globals.css'
import { Inter } from 'next/font/google'
import AppContextProvider from "@/provider/AppContextProvider";
import Header from "@/components/organisms/Header/Header";
import ThemeWrapper from "@/components/organisms/ThemeWrapper/ThemeWrapper";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Whispers',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // dynamic import is needed to access window.localStorage
  const DynamicThemeWrapper = dynamic(() => import('@/components/organisms/ThemeWrapper/ThemeWrapper'), {
    ssr: false
  })

  return (
    <html lang="en">
    <AppContextProvider>
      <body className={`${inter.className}`}>
      <DynamicThemeWrapper>
        <Header></Header>
        <main>
          {children}
        </main>
      </DynamicThemeWrapper>
      </body>
    </AppContextProvider>
    </html>
  )
}
